"""
SBW CLI Tool Package
SBWv1.i2 Mark I Prototype

This package provides tools for decoding, decrypting, and visualizing
SBW (Shoot-By-Wire) log files generated by embedded firmware.

Core functionality:
- AES-GCM decryption
- LZ4/Heatshrink decompression  
- TLV parsing
- Data export (CSV/JSON)
- Visualization
"""

__version__ = "1.0.0"
__author__ = "Demond Balentine"
__email__ = "demond@balentine-tech.com"

from .core.decoder import SBWDecoder
from .core.crypto import CryptoProcessor  
from .core.compression import CompressionProcessor
from .core.tlv_parser import TLVParser
from .core.exporter import DataExporter
from .core.visualizer import DataVisualizer

__all__ = [
    "SBWDecoder",
    "CryptoProcessor", 
    "CompressionProcessor",
    "TLVParser",
    "DataExporter", 
    "DataVisualizer"
]